mkdir -p node
# 自动赋予执行权限（虽然这一步通常只需要执行一次）
chmod +x "$0"

# 在后台并行运行三个训练实验
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_bn0_CustomGINEConv-all.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_bn0_CustomGINEConv-attn.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual 1 --g_bn 0 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_bn0_CustomGINEConv-g_bn.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual 0 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_bn0_CustomGINEConv-residual.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.0 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_bn0_CustomGINEConv-drop.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 0 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_bn0_CustomGINEConv-ffn.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 3 --use_bn 0 --residual 0 --g_bn 0 --g_drop 0.0 --g_ffn 0 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_bn0_gine-none.log &

# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_bn0_CustomGCNConv-all.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_bn0_CustomGCNConv-attn.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual 1 --g_bn 0 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_bn0_CustomGCNConv-g_bn.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual 1 --g_bn 0 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_bn0_CustomGCNConv-residual.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.0 --g_ffn 1 --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_bn0_CustomGCNConv-drop.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 0 --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_bn0_CustomGCNConv-ffn.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 3 --use_bn 0 --residual 0 --g_bn 0 --g_drop 0.0 --g_ffn 0 --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_bn0_CustomGCNConv-none.log &

# python main.py --net_only 0 --neg_edge_ratio 0.5 --task_level edge --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/bn0_CustomGCNConv-all.log &
# python main.py --net_only 0 --neg_edge_ratio 0.5 --task_level edge --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/bn0_CustomGCNConv-attn.log &
# python main.py --net_only 0 --neg_edge_ratio 0.5 --task_level edge --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual 0 --g_bn 0 --g_drop 0.0 --g_ffn 0 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/bn0_CustomGCNConv-none.log &
# python main.py --net_only 0 --neg_edge_ratio 0.5 --task_level edge --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/CustomGINEConv-all.log &
# python main.py --net_only 0 --neg_edge_ratio 0.5 --task_level edge --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/CustomGINEConv-attn.log &
# python main.py --net_only 0 --neg_edge_ratio 0.5 --task_level edge --task regression --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 3 --use_bn 0 --residual 0 --g_bn 0 --g_drop 0.0 --g_ffn 0 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/CustomGINEConv-none.log &

# python main.py --net_only 1 --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 1 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node/node_class_bn0_CustomGCNConv-all.log &
# python main.py --net_only 1 --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 1 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node/node_class_bn0_CustomGCNConv-attn.log &
# python main.py --net_only 1 --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual 0 --g_bn 0 --g_drop 0.0 --g_ffn 0 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 1 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node/node_class_bn0_CustomGCNConv-none.log &
# python main.py --net_only 1 --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 3 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 1 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node/node_class_CustomGINEConv-all.log &
# python main.py --net_only 1 --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual 1 --g_bn 1 --g_drop 0.3 --g_ffn 1 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 1 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node/node_class_CustomGINEConv-attn.log &
# python main.py --net_only 1 --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 3 --use_bn 0 --residual 0 --g_bn 0 --g_drop 0.0 --g_ffn 0 --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type None --num_heads 1 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_CustomGINEConv-none.log &

# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual True --g_bn False --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_bn0_CustomGCNConv-g_bn.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual False --g_bn True --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_bn0_CustomGCNConv-residual.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual True --g_bn True --g_drop 0.0 --g_ffn True --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_bn0_CustomGCNConv-drop.log &
# python main.py --net_only False --neg_edge_ratio 0.0 --task_level node --task classification --lr 0.00008 --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual True --g_bn True --g_drop 0.3 --g_ffn False --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/node_class_bn0_CustomGCNConv-ffn.log &


# python main.py --task regression --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual True --g_bn True --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGatedGCN --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn0_CustomGatedGCN-norm.log &

# python main.py --task regression --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 0 --residual True --g_bn True --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/use1_CustomGCNConv.log &
# python main.py --task regression --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual False --g_bn False --g_drop 0.0 --g_ffn False --model gps_attention --local_gnn_type CustomGCNConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/use0_CustomGCNConv.log &
# python main.py --task regression --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual True --g_bn True --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/use1_CustomGINEConv.log &
# python main.py --task regression --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual False --g_bn False --g_drop 0.0 --g_ffn False --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+timing_ctrl+array_128_32_8t+ultra8t+sandwich  | tee gnn_plus_ln/use0_CustomGINEConv.log &
# python main.py --task regression --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --model gps_attention --local_gnn_type GAT --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/GAT.log &

# python main.py --task_level edge --task regression --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 0 --residual True --g_bn True --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGatedGCN --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn0_CustomGatedGCN.log &
# # python main.py --task regression --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 0 --residual True --g_bn False --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGatedGCN --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn0_CustomGatedGCN-g_bn.log &
# # python main.py --task regression --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual False --g_bn True --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGatedGCN --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn0_CustomGatedGCN-residual.log &
# # python main.py --task regression --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual True --g_bn True --g_drop 0.0 --g_ffn True --model gps_attention --local_gnn_type CustomGatedGCN --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn0_CustomGatedGCN-drop.log &
# python main.py --task_level edge --task regression  --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual False --g_bn False --g_drop 0.0 --g_ffn False --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn0_CustomGINEConv-none.log &
# # python main.py --task regression --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual True --g_bn True --g_drop 0.3 --g_ffn False --model gps_attention --local_gnn_type CustomGatedGCN --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn0_CustomGatedGCN-ffn.log &
# python main.py --task_level edge --task regression --layer_norm 1 --batch_norm 0 --gpu 1 --use_bn 0 --residual True --g_bn True --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGatedGCN --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn0_CustomGatedGCN-attn.log &
# python main.py --task_level edge --task regression --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual False --g_bn False --g_drop 0.0 --g_ffn False --model gps_attention --local_gnn_type CustomGatedGCN --attn_dropout 0 --global_model_type None --num_heads 2 --dataset ssram+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn0_CustomGatedGCN-none.log &
# python main.py --task_level edge --task classification --layer_norm 1 --batch_norm 0 --gpu 3 --use_bn 0 --residual False --g_bn False --g_drop 0.0 --g_ffn False --model gps_attention --local_gnn_type CustomGatedGCN --attn_dropout 0 --global_model_type None --num_heads 2 --dataset ssram+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn0_class_CustomGatedGCN-none.log &
# python main.py --task regression --layer_norm 0 --batch_norm 0 --gpu 1 --use_bn 1 --residual True --g_bn True --g_drop 0.3 --g_ffn True --model regression --local_gnn_type CustomGatedGCN --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn1_class_CustomGatedGCN-norm.log &
# python main.py --task regression --layer_norm 0 --batch_norm 0 --gpu 3 --use_bn 1 --residual True --g_bn True --g_drop 0.3 --g_ffn True --model regression --local_gnn_type CustomGatedGCN --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/bn1_CustomGatedGCN-norm.log &


# 等待所有后台进程完成
wait

echo "All training processes completed."

# python main.py --task regression --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 1 --residual True --g_bn True --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGatedGCN --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/CustomGatedGCN-attn.log &
# python main.py --task classification --layer_norm 1 --batch_norm 0 --gpu 0 --use_bn 1 --residual True --g_bn True --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGatedGCN --attn_dropout 0.7 --global_model_type None --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee gnn_plus_ln/class_CustomGatedGCN-attn.log &

# python main.py --task_level node --task regression --layer_norm 1 --batch_norm 0 --gpu 3 --use_bn 0 --net_only False --neg_edge_ratio 0.5 --residual True --g_bn True --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/text.log &
# python main.py --task_level node --neg_edge_ratio 0.0 --task classification --layer_norm 1 --batch_norm 0 --gpu 2 --use_bn 0 --residual True --g_bn True --g_drop 0.3 --g_ffn True --model gps_attention --local_gnn_type CustomGINEConv --attn_dropout 0.7 --global_model_type Transformer --num_heads 2 --net_only True --dataset ssram+digtime+timing_ctrl+array_128_32_8t+ultra8t+sandwich | tee node_gnn_plus_ln/test.log